model:
  target: RandAR.model.maskgit_tokenizer.MaskGITTokenizer
  params:
    channel_mult: [1, 1, 2, 2, 4]
    num_resolutions: 5
    dropout: 0.0
    hidden_channels: 128
    num_channels: 3
    z_channels: 256
    num_embeddings: 1024
    embedding_dim: 256
    commitment_cost: 0.25